// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using SpbBuildingAgeMaps.DataModel;
using System;

namespace SpbBuildingAgeMaps.Migrations
{
    [DbContext(typeof(BuildingContext))]
    partial class BuildingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("SpbBuildingAgeMaps.DataModel.Building", b =>
                {
                    b.Property<int>("BuildingId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BuildYear");

                    b.Property<string>("BuildingType");

                    b.Property<string>("District");

                    b.Property<string>("RawAddress");

                    b.HasKey("BuildingId");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("SpbBuildingAgeMaps.DataModel.CoordData", b =>
                {
                    b.Property<int>("CoordDataId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BuildingId");

                    b.Property<string>("Source");

                    b.Property<double?>("X");

                    b.Property<double?>("Y");

                    b.Property<double?>("Z");

                    b.HasKey("CoordDataId");

                    b.HasIndex("BuildingId");

                    b.ToTable("CoordsData");
                });

            modelBuilder.Entity("SpbBuildingAgeMaps.DataModel.OsmObject", b =>
                {
                    b.Property<int>("OsmObjectId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CoordDataId");

                    b.Property<int>("ExternalOsmObjectId");

                    b.Property<string>("Source");

                    b.Property<int>("Type");

                    b.HasKey("OsmObjectId");

                    b.HasIndex("CoordDataId");

                    b.ToTable("OsmObjects");
                });

            modelBuilder.Entity("SpbBuildingAgeMaps.DataModel.CoordData", b =>
                {
                    b.HasOne("SpbBuildingAgeMaps.DataModel.Building", "Building")
                        .WithMany("CoordsData")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SpbBuildingAgeMaps.DataModel.OsmObject", b =>
                {
                    b.HasOne("SpbBuildingAgeMaps.DataModel.CoordData", "CoordData")
                        .WithMany("OsmObjects")
                        .HasForeignKey("CoordDataId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
